In [1]:
# Broadcasting in python
import numpy as np
a = np.array([1,2,3])
b = a + 5
print(b)
M = np.ones((3,3))
# Here the vector a is stretched to a 2-d matrix
print(M+a)

[6 7 8]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
